# Generated by Django 4.2.2 on 2023-06-27 14:02

import django.core.validators
from django.db import migrations, models
import github.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGitHubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Project name')),
                ('url', github.fields.GitURLField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('use_deploy_key', models.BooleanField(default=False, help_text='Installer SSH key is added to the repository as a deploy key')),
                ('port', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Project port')),
                ('ssh_key', models.TextField(blank=True, default=None, null=True, verbose_name='SSH Private Key')),
                ('ssh_key_passphrase', models.TextField(blank=True, default=None, null=True, verbose_name='SSH Private Key Passphrase')),
                ('ssh_pubkey', models.TextField(blank=True, default=None, null=True, verbose_name='SSH Public Key')),
                ('git_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Git username')),
                ('git_password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Git password')),
                ('is_full_reanalyze_scheduled', models.BooleanField(default=False, help_text='The project can analyzed again from scratch in case flag is set')),
                ('last_error', models.TextField(blank=True, help_text='Last processing task error', null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
