# Generated by Django 4.2.2 on 2023-06-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigithubproject',
            name='is_full_reanalyze_scheduled',
        ),
    ]
