# Generated by Django 4.2.2 on 2023-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_remove_aigithubproject_is_full_reanalyze_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigithubproject',
            name='last_commit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last commit'),
        ),
    ]
